### ISSUE TITLE
question: how to extract individual files

### ISSUE THREAD

**Issue by setop** [PackOrganization/Pack#12]
It seems the overweight compare to Tar+Zstd is due to the fact that files are compressed individually, like for Zip or 7zip.

How to extract individual files, based on name, path or pattern ?

**Comment by thousandsofthem** [comment]
Having usage examples in Readme would be useful, empty Readme does not provide any confidence in the project.

https://pack.ac/cli-documentation



> `--include` Specifying a file or folder in a Pack file to unpack or list. It can be set to a path or an ID. It is allowed to be used more than once. It will use an optimized algorithm to process each item just once.

**Comment by OttoCoddo** [comment]
@setop tar.zst compresses the whole file and cannot give you random access.
For Pack, you can use it like:
Get a list of all items:
`pack -i ./test.pack --list`
Unpack a file inside a Pack file:
`pack -i ./test.pack --include=/a/file.txt`
Use an ID instead of a path to include:
`pack -i ./test.pack --include=5`
Unpack multiple files and folders:
`pack -i ./test.pack --include=/a/file.txt --include=/a/folder/`

@thousandsofthem Thank you for the help and the note. The base of the Pack project is the website; this repository is for both development and communication.
I understand your concern, but because I did not want double documentation, I chose documenting on the website.
