### ISSUE TITLE
Random Access?

### ISSUE THREAD

**Issue by DavidBuchanan314** [PackOrganization/Pack#3]
The "Notes" section of the website mentions support for random access, but unless I'm mistaken, the format does not actually support this. Does it?

**Comment by DavidBuchanan314** [comment]
Ah, ok, I see this problem is basically solved by splitting into ~8MB chunks. Performance would be bad if you wanted to read *small* subsections, but it is still random access I suppose.

**Comment by OttoCoddo** [comment]
8 MB chunks are the default; Pack may choose smaller or bigger (16 MB for many small files or 32 MB for Hard Press).

Random access is proper as unpacking steps take into account what you want and decompress a Content just once for many neighbouring files.
But even for reading just one file, here is an example: if I want to extract just a .c file from the whole codebase of Linux, it can be done (on my machine) in 30 ms, compared to near 500 ms for WinRAR or 2500 ms for tar.gz. And it will just worsen when you count encryption.
For now, Pack encryption is not public, but when it is, you can access a file in a locked Pack file in a matter of milliseconds rather than seconds.
